### ISSUE TITLE
User Interface Screen Designs

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docs#15]
Someone with creative ability to design web pages should create a consistent layout and design. Once the components have been designed, the design can be implemented by other developers.

The functional requirements will impact the design:
- view nodes in the swarm
- view containers running on nodes in the swarm
- etc.. (TODO)

**Comment by Mimels** [comment]
I agree and we should keep the design simple but elegant. There are quite a few templates (these are Angular 2 or 4 but they will probably still spark some creativity: https://bootstrapbay.com/blog/free-angular-templates/ and https://colorlib.com/wp/angular-2-components/) that we can look at. The first link lists templates for dashboards and the other link is just for inspiration when it comes to components. This is also a colour scheme designer (http://paletton.com/#uid=10P0u0kllllaFw0g0qFqFg0w0aF) to look at.

**Comment by egeldenhuys** [comment]
Moving to `docks-ui`
