### ISSUE TITLE
Deployment Diagram

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docs#2]
Current deployment diagram. Source is on Google Drive for now.

![image](https://user-images.githubusercontent.com/5778739/37272328-fcf1dfde-25de-11e8-860d-45a5830d7aa5.png)

**Comment by egeldenhuys** [comment]
I propose the following workflow:
1. Manually create a swarm using Docker Swarm
2. Deploy Docks on the manager node
3. Use Docks to deploy Docks as a global service on the workers. This will allow us to extract arbitrary information from any node in the swarm. Care needs to be taken that the Docks instance running on the manager is not removed when we remove it from other nodes for some reason. Perhaps using swarm constraints?
4. Use Docks to manage the swarm in greater detail than the native swarm.

**Comment by EmpireMuncher** [comment]
@egeldenhuys Scanned through it and sounds right, will look more into detail tomorrow evening after my test and ask questoins if something pops up

**Comment by egeldenhuys** [comment]
The Architecture will be discussed in #4
