### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docs#4]
I propose the following workflow:
1. Manually create a swarm using Docker Swarm
2. Deploy Docks on the manager node
3. Use Docks to deploy Docks as a global service on the workers. This will allow us to extract arbitrary information from any node in the swarm. Care needs to be taken that the Docks instance running on the manager is not removed when we remove it from other nodes for some reason. Perhaps using swarm constraints?
4. Use Docks to manage the swarm in greater detail than the native swarm.

To use the Docks API on any node, the client has to be authenticated. Since the manager will be the entry point, perhaps we can use the existing swarm infrastructure for authentication.

**Comment by devosray** [comment]
Why would we deploy the Docks API to all nodes in the swarm? Why would it be needed that each node runs the complete REST API? What if we want to add a custom database? Would that be shared across all the nodes as well?

**Comment by egeldenhuys** [comment]
### Manager
- Runs Docks Manager API - Authenticated (username/password) API that proxies commands to Docker
- Runs Docks Worker API - Authenticated (Docker Swarm infrastructure) API that extracts information from the host and performs custom actions

### Worker
- Only runs Docks Worker API

----

Either we split the API into two different containers, and access the services on different ports, or we serve both from the same container but disable the management API by default.

**Comment by Jason-vh** [comment]
Note that the entire swarm can be managed from a manager node - there should be no reason to run additional services on the worker nodes.

My advice would be to run a API on at least one manager node. This API would handle the REST requests as well as manage the swarm through the Docker API on that node. Ensuring that the API is running on a manage node could be done through Swarm's constraints.

This API could then be replicated over the manager nodes through Swarm's scaling system for redundancy. Requests to the API would be load balanced through Swarm's built-in loadbalancing.

**Comment by egeldenhuys** [comment]
I see now the Docker API provides an endpoint to get system information (CPU usage, Memory usage, NET I/O etc), so we so do not need to run additional services on workers as @Jason-vh said.

Thank you for pointing that out

**Comment by egeldenhuys** [comment]
Architecture is reflected in the Deployment Diagram (TripleParity/docs/pull/5)
